config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  #get 'contacts/new'
  get 'about', to: 'pages#about'
  get 'contact-us', to: 'contacts#new', as: 'new_contact'
  resources :contacts, only: :create

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates :name, presence: true
  validates :email, presence: true
  validates :comments, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  # Get request to /contact-us
  # Show new contact form
  def new
    @contact = Contact.new
  end

  # POST request / contacts
  def create
    # Mass assignment of form fiedl to contact object
    @contact = Contact.new(contact_params)
    if @contact.save
      # store form field via parameters into variables
      name = params[:contact][:name]
      email = params[:contact][:email]
      body = params[:contact][:comments]
      ContactMailer.contact_email(name, email, body).deliver
      flash[:success] =  "Your message has been sent"
      redirect_to new_contact_path
    else
      flash[:danger] = @contact.errors.full_messages.join(", ")
      redirect_to new_contact_path
    end
  end

  private
    def contact_params
      params.require(:contact).permit(:name, :email, :comments)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/contacts/new.html.erb
<div class="container">
<div class="row">
    <h3 class="text-center">Contact us</h3>
      <div class="col-md-4 col-md-offset-4">
        <div class="well">
        <%= form_for @contact do |f| %>
          <div class="form-group">
            <%= f.label :name %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :email %>
            <%= f.email_field :email, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :comments %>
            <%= f.text_area :comments, class: 'form-control' %>
          </div>

          <%= f.submit "Send", class: 'btn btn-success' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AbilMatch</title>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,500" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default navbar-static-top" role="navigation">
      <div class='container'>
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-nav-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to root_path, class: "navbar-brand" do %>
            <i class="fa fa-group"></i>
            AbilMatch
          <% end %>
        </div>
        <div class="collapse navbar-collapse" id="main-nav-collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "About", about_path %></li>
            <li><%= link_to "Contact us", new_contact_path %></li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div>
    </nav>
    <div class="container">
      <div class="row">
        <div class="col-md-4 col-md-offset-4 text-center">
          <% flash.each do |type, message| %>
            <%= content_tag :div, message, class: "alert alert-#{type}"%>
          <% end %>
        </div>
      </div>
    </div>

    <%= yield %>

  </body>
</html>

app/views/pages/about.html.erb
<div class="container text-center">
  <h1>About Page</h1>
  <p>We are DevMatch. Our company focuses on creating an exclusive community
  developers and entrepreneurs to meet.</p>
</div>

app/views/pages/home.html.erb
<div class="home-callout text-center container-fluid">
  <h1>Welcome to DevMatch</h1>
  <h3>A membership site where entrepreneurs can meet developers.</h3>
</div>